// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package di

import (
	"go_api_boilerplate/domain/interactor"
	"go_api_boilerplate/infra/database"
	"go_api_boilerplate/adapter/gateway"
	"go_api_boilerplate/adapter/handler"
)

// Injectors from wire.go:

func InitUserApp() *handler.UserHandler {
	dbHandler := database.NewMysqlHandler()
	userRepository := gateway.NewUserRepository(dbHandler)
	userUseCase := interactor.NewUserUseCase(userRepository)
	userHandler := handler.NewUserHandler(userUseCase)
	return userHandler
}
